steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'TOKEN=${TOKEN}'
    - 'DEFAULT_GUILD_ID=${DEFAULT_GUILD_ID}'
    - 'REACTION_ROLES_CHANNEL_ID=${REACTION_ROLES_CHANNEL_ID}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"